version: "3.8"
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - PGUSER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "3030:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
volumes:
  db:
    driver: local
