import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/globals.css';
import Header from '../components/header';
import Footer from '../components/footer';
import { Stack, Container } from '@mui/material';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'FluxSend',
  description: 'Generated by FluxSend',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Stack sx={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
          <Header />
          <Container sx={{ flex: '1', display: 'flex', flexDirection: 'column', justifyContent: 'center', bgcolor: '#1a1a1a', height: '90vh', paddingBottom: '20vh' }}>{children}</Container>
          <Footer />
        </Stack>
      </body>
    </html>
  );
}
